import React, { useState, useEffect } from 'react';
import { PromptItem, PromptStatus } from '../types';
import { generatePromptVariations } from '../services/geminiService';
import { Plus, Trash2, Edit2, Play, Loader2, Sparkles, AlertCircle } from 'lucide-react';

interface PromptRefinementProps {
  initialRequest: string;
  onNext: (prompts: PromptItem[]) => void;
  onBack: () => void;
}

const PromptRefinement: React.FC<PromptRefinementProps> = ({ initialRequest, onNext, onBack }) => {
  const [prompts, setPrompts] = useState<PromptItem[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Initialize prompts on mount
  useEffect(() => {
    const fetchPrompts = async () => {
      try {
        setIsLoading(true);
        const variations = await generatePromptVariations(initialRequest);
        
        const newPrompts: PromptItem[] = variations.map(text => ({
          id: crypto.randomUUID(),
          text,
          originalRequest: initialRequest,
          status: PromptStatus.PENDING,
          pilotSamples: []
        }));
        
        setPrompts(newPrompts);
      } catch (err) {
        setError("Failed to generate prompt variations. Please try again.");
      } finally {
        setIsLoading(false);
      }
    };

    fetchPrompts();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []); // Run once

  const handleAddPrompt = () => {
    setPrompts([
      ...prompts,
      {
        id: crypto.randomUUID(),
        text: "New prompt...",
        originalRequest: initialRequest,
        status: PromptStatus.PENDING,
        pilotSamples: []
      }
    ]);
  };

  const handleDeletePrompt = (id: string) => {
    setPrompts(prompts.filter(p => p.id !== id));
  };

  const handleUpdatePrompt = (id: string, text: string) => {
    setPrompts(prompts.map(p => p.id === id ? { ...p, text } : p));
  };

  if (isLoading) {
    return (
      <div className="flex flex-col items-center justify-center h-full space-y-4">
        <Loader2 className="animate-spin text-indigo-500" size={48} />
        <h2 className="text-xl font-semibold text-slate-300">Designing Prompts...</h2>
        <p className="text-slate-500">PEA Agent is analyzing your request and creating variations.</p>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex justify-between items-end">
        <div>
            <h1 className="text-3xl font-bold text-white mb-2">Prompt Engineering</h1>
            <p className="text-slate-400">Review and refine the generated prompts before starting the Pilot Run.</p>
        </div>
        <button 
            onClick={handleAddPrompt}
            className="flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 rounded-lg text-sm font-medium transition-colors"
        >
            <Plus size={16} /> Add Custom Prompt
        </button>
      </div>

      {error && (
        <div className="p-4 bg-red-900/20 border border-red-800 rounded-lg flex items-center gap-3 text-red-200">
            <AlertCircle size={20} />
            {error}
        </div>
      )}

      <div className="space-y-4">
        {prompts.map((prompt, index) => (
          <div key={prompt.id} className="group relative bg-slate-900 border border-slate-800 rounded-xl p-4 transition-all hover:border-indigo-500/50 hover:shadow-lg hover:shadow-indigo-500/10">
            <div className="flex gap-4">
                <div className="mt-1">
                    <div className="w-8 h-8 rounded-full bg-indigo-500/20 text-indigo-400 flex items-center justify-center text-sm font-bold border border-indigo-500/30">
                        {index + 1}
                    </div>
                </div>
                <div className="flex-1">
                    <textarea 
                        className="w-full bg-transparent border-none text-slate-200 focus:ring-0 p-0 resize-none text-base leading-relaxed h-auto min-h-[80px]"
                        value={prompt.text}
                        onChange={(e) => handleUpdatePrompt(prompt.id, e.target.value)}
                    />
                    <div className="mt-2 flex items-center gap-2 text-xs text-slate-500">
                       <Sparkles size={12} />
                       <span>Generated by Gemini 2.5 Flash</span>
                    </div>
                </div>
                <div className="flex flex-col gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                    <button 
                        onClick={() => handleDeletePrompt(prompt.id)}
                        className="p-2 text-slate-500 hover:text-red-400 hover:bg-red-400/10 rounded-lg transition-colors"
                        title="Delete Prompt"
                    >
                        <Trash2 size={18} />
                    </button>
                </div>
            </div>
          </div>
        ))}
      </div>

      <div className="flex justify-between pt-8 border-t border-slate-800">
        <button
            onClick={onBack}
            className="px-6 py-3 text-slate-400 hover:text-white font-medium transition-colors"
        >
            Back
        </button>
        <button
            onClick={() => onNext(prompts)}
            disabled={prompts.length === 0}
            className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed text-white px-8 py-3 rounded-lg font-medium transition-all shadow-lg shadow-indigo-600/20"
        >
            Run Pilot Validation
            <Play size={18} fill="currentColor" />
        </button>
      </div>
    </div>
  );
};

export default PromptRefinement;